# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\tmypackage\"-\n\x0b\x44\x61taRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xcd\x02\n\x0b\x44\x61taService\x12<\n\x07\x41\x64\x64\x44\x61ta\x12\x16.mypackage.DataRequest\x1a\x17.mypackage.DataResponse\"\x00\x12<\n\x07GetData\x12\x16.mypackage.DataRequest\x1a\x17.mypackage.DataResponse\"\x00\x12?\n\nUpdateData\x12\x16.mypackage.DataRequest\x1a\x17.mypackage.DataResponse\"\x00\x12?\n\nDeleteData\x12\x16.mypackage.DataRequest\x1a\x17.mypackage.DataResponse\"\x00\x12@\n\x0bGetDataList\x12\x16.mypackage.DataRequest\x1a\x17.mypackage.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=25
  _globals['_DATAREQUEST']._serialized_end=70
  _globals['_DATARESPONSE']._serialized_start=72
  _globals['_DATARESPONSE']._serialized_end=103
  _globals['_DATASERVICE']._serialized_start=106
  _globals['_DATASERVICE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
